# Generated by Django 3.0.2 on 2020-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('popularity', models.IntegerField(default=0)),
                ('director', models.CharField(default='N/A', max_length=50)),
                ('imdb_score', models.FloatField(blank=True, default=None, null=True)),
                ('genre', models.ManyToManyField(to='movieapp.Genre')),
            ],
        ),
    ]
